version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-clojure
    volumes:
      - .:/app
    ports:
      - "3001:8080"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "3000:8080"
    depends_on:
      - app

